export { default as BuildingIcon } from './Building';
export { default as CardsIcon } from './Cards';
export { default as CheckIcon } from './Check';
export { default as CodeIcon } from './Code';
export { default as GaugeIcon } from './Gauge';
export { default as InfoIcon } from './Info';
export { default as PlusIcon } from './Plus';
export { default as WalletIcon } from './Wallet';
export { default as XCircleIcon } from './XCircle';
